export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  ORG_MEMBER: 'ORG_MEMBER',
  PLAYER: 'PLAYER',
  COACH: 'COACH',
  OFFICIAL: 'OFFICIAL'
} as const;

export const PERMISSION_KEYS = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_ROLES: 'VIEW_ROLES',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
  MANAGE_ORGANIZATIONS: 'MANAGE_ORGANIZATIONS',
  VIEW_ORGANIZATIONS: 'VIEW_ORGANIZATIONS',
  MANAGE_TOURNAMENTS: 'MANAGE_TOURNAMENTS',
  VIEW_TOURNAMENTS: 'VIEW_TOURNAMENTS'
} as const;

export const COLLECTION_NAMES = {
  USERS: 'Users',
  ROLES: 'Roles',
  PERMISSIONS: 'Permissions',
  ORGANIZATIONS: 'Organizations',
  ORGANIZATION_MEMBERSHIPS: 'OrganizationMemberships',
  AUDIT_LOGS: 'AuditLogs',
  TOURNAMENTS: 'Tournaments',
  MATCHES: 'Matches'
} as const;

export const ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',
  MONGODB_URI: 'MONGODB_URI',
  JWT_SECRET: 'JWT_SECRET',
  NEXT_PUBLIC_APP_URL: 'NEXT_PUBLIC_APP_URL'
} as const;

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100
} as const;

export const VALIDATION_LIMITS = {
  MAX_NAME_LENGTH: 100,
  MAX_DESC_LENGTH: 1000,
  MIN_PASSWORD_LENGTH: 8,
  MAX_EMAIL_LENGTH: 255
} as const;

export const DEFAULT_SETTINGS = {
  TIMEZONE: 'UTC',
  CURRENCY: 'USD',
  LANGUAGE: 'en'
} as const;

export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION'
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
} as const;

export const APP_CONSTANTS = {
  APP_NAME: 'DAFT Arena',
  SUPPORT_EMAIL: 'support@daftarena.com'
} as const;
